#!/usr/bin/env sh
set -e

LOCATION="$HOME/Pictures/Screenshots/Screenshot $(date +%Y-%m-%d\ %H%M%S).png"
if [ "$1" = "1" ]; then
  SLURP="$(slurp)"
  canberra-gtk-play -i screen-capture &
  grim -c -l 9 -g "$SLURP" "$LOCATION"
else
  canberra-gtk-play -i screen-capture &
  grim -c -l 9 "$LOCATION"
fi

wl-copy --type image/png < "$LOCATION"
notify-send -u "normal" "Screenshot saved!" 