#!/bin/bash

LOCATION="$HOME/Pictures/Screenshots/Screenshot $(date +%Y-%m-%d\ %H%M%S).png"

# Region
if [ "$1" = "-r" ]; then
  hyprpicker -rz &
  sleep 0.02

  SLURP="$(slurp)"
  STATUS=$?

  if [ $STATUS -ne 0 ]; then
    pkill hyprpicker
    exit 1
  fi

  canberra-gtk-play -i screen-capture &
  grim -g "$SLURP" "$LOCATION" &
  GRIM_PID=$!
  
  pkill hyprpicker
# Full Screen
else
  SCREEN=$(swaymsg -t get_outputs --raw | jq '. | map(select(.focused == true)) | .[0].name' -r)
  canberra-gtk-play -i screen-capture &
  grim -o "$SCREEN" "$LOCATION"
fi

wait $GRIM_PID
wl-copy < "$LOCATION"
notify-send -u "normal" "Screenshot saved" "Image copied to the clipboard"