#!/bin/bash
set -e

LOCATION="$HOME/Pictures/Screenshots/Screenshot $(date +%Y-%m-%d\ %H%M%S).png"
# Selection
if [ "$1" = "1" ]; then
  SLURP="$(slurp)"
  canberra-gtk-play -i screen-capture &
  grim -g "$SLURP" "$LOCATION"
# Full Screen
else
  SCREEN=$(swaymsg -t get_outputs --raw | jq '. | map(select(.focused == true)) | .[0].name' -r)
  canberra-gtk-play -i screen-capture &
  grim -o "$SCREEN" "$LOCATION"
fi

wl-copy < "$LOCATION"
notify-send -u "normal" "Screenshot saved!"