#!/bin/sh

if ! [ "$1" = "--no-daemon" ]; then
  "$0" --no-daemon "$@" > /dev/null 2>&1 &
  exit 0
fi

SWAY_PID=$(pgrep -u "$USER" -x sway)
pid_kill_list=

while read -r pid; do
  # Ignore self/thread-self
  case "$pid" in
    ''|*[!0-9]*) continue ;;
  esac

  # Don't kill self
  if [ "$pid" -eq "$$" ]; then continue; fi
  
  ppid=$(ps -p "$pid" -o ppid= | tr -d ' ')
  if [ "$ppid" = "$SWAY_PID" ] || [ "$ppid" = "1" ]; then
    pid_kill_list="$pid_kill_list$pid "
  fi
done <<EOF
$(grep -l "SWAYSOCK=$SWAYSOCK" /proc/*/environ 2>/dev/null | cut -d/ -f3)
EOF

pid_kill_list=$(echo "$pid_kill_list" | xargs)
# shellcheck disable=SC2086
kill $pid_kill_list
# shellcheck disable=SC2086
waitpid $pid_kill_list

swaymsg exit
