#!/bin/bash

canberra-gtk-play -i desktop-login &

udevadm monitor --udev --property | \
while IFS= read -r line; do
  # Event properties
  if [[ "$line" == ACTION=* ]]; then
    action="${line#ACTION=}"
  elif [[ "$line" == SUBSYSTEM=* ]]; then
    subsystem="${line#SUBSYSTEM=}"
  elif [[ "$line" == DEVTYPE=* ]]; then
    devtype="${line#DEVTYPE=}"
  fi

  # Event description ends with empty line
  if [[ -z "$line" ]]; then
    if [[ "$subsystem" == "usb" && "$devtype" == "usb_device" ]]; then
      if [[ "$action" == "add" ]]; then
        canberra-gtk-play -i device-added &
      elif [[ "$action" == "remove" ]]; then
        canberra-gtk-play -i device-removed &
      fi
    fi

    # Reset variables for next event
    action=""
    subsystem=""
    devtype=""
  fi
done
