#!/bin/sh

udev_pid=

canberra-gtk-play -i desktop-login &

trap_exit() {
  kill "$udev_pid" 2>/dev/null
  exit
}
trap trap_exit INT TERM EXIT

udevadm monitor --udev --property | \
while IFS= read -r line; do
  # Event properties
  case "$line" in
    ACTION=*)
     action="${line#ACTION=}" ;;
    SUBSYSTEM=*)
      subsystem="${line#SUBSYSTEM=}" ;;
    DEVTYPE=*)
      devtype="${line#DEVTYPE=}" ;;
  esac

  # Event description ends with empty line
  if [ -z "$line" ]; then
    if [ "$subsystem" = "usb" ] && [ "$devtype" = "usb_device" ]; then
      if [ "$action" = "add" ]; then
        canberra-gtk-play -i device-added &
      elif [ "$action" = "remove" ]; then
        canberra-gtk-play -i device-removed &
      fi
    fi

    # Reset variables for next event
    action=""
    subsystem=""
    devtype=""
  fi
done &
udev_pid=$!

wait "$udev_pid"
