bindsym $main+T            exec footclient
bindsym $main+E            exec footclient yazi

bindsym Print              exec ~/.config/sway/scripts/screenshot
bindsym $sec+S             exec ~/.config/sway/scripts/screenshot -r

bindsym $sec+C             exec hyprpicker -a

bindsym $main+Space        exec rofi -show drun -run-command "swaymsg 'exec {cmd}'"
bindsym $main+C            exec swaync-client -t
bindsym $main+V            exec ~/.config/sway/scripts/cliphist-menu
bindsym $main+semicolon    exec rofi -show emoji

bindsym $main+BRACKETLEFT  exec obs-cmd -w "obsws://localhost:6767/$(jq -r '.server_password' ~/.config/obs-studio/plugin_config/obs-websocket/config.json)" recording toggle
bindsym $main+BRACKETRIGHT exec obs-cmd -w "obsws://localhost:6767/$(jq -r '.server_password' ~/.config/obs-studio/plugin_config/obs-websocket/config.json)" recording toggle-pause
bindsym $main+RETURN       exec obs-cmd -w "obsws://localhost:6767/$(jq -r '.server_password' ~/.config/obs-studio/plugin_config/obs-websocket/config.json)" replay save
