bindsym $panic+g exec systemctl --user stop waybar; exec dinitctl stop waybar; mode "guest"
mode "guest" {
  bindsym $panic+Escape exec systemctl --user start waybar; exec dinitctl start waybar; mode "default"
}