[indicator.colors.station]
connected=white
connecting=gray
disconnected=gray

[indicator.colors.ap]
up=white
down=gray

[indicator.colors.adhoc]
up=white
down=gray

[indicator.colors.disabled]
device=gray
adapter=gray

[network.colors]
connected=white
connecting=gray
known=white
unknown=gray
hidden=gray