exec /usr/lib/xdg-desktop-portal
exec /usr/lib/xdg-desktop-portal-wlr
exec /usr/lib/xdg-desktop-portal-gtk

exec /usr/bin/autotiling
exec /usr/bin/awww-daemon
exec ~/.config/sway/scripts/cliphist
exec /usr/bin/foot -s
exec /usr/bin/gamemoded
exec /usr/bin/lxqt-policykit-agent
exec /usr/bin/swayidle
exec /usr/bin/swaync
exec ~/.config/sway/scripts/swaysounds
exec /usr/bin/waybar

