# ----------------- #
# --- AUTOSTART --- #
# ----------------- #

# --- Services --- #
# Clipboard persistence
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec wl-clip-persist --clipboard regular

exec wal -R
exec swayidle
exec ~/.config/sway/system-soundsd
exec ~/.config/sway/sway-screenshare-fixd

# Boot sound
exec canberra-gtk-play -i desktop-login