#exec sh -c "dinitctl setenv XDG_SESSION_ID WAYLAND_DISPLAY DISPLAY SWAYSOCK I3SOCK && dinitctl start sway-session"
exec /usr/bin/autotiling
exec /usr/bin/awww-daemon
exec ~/.config/sway/scripts/cliphist
exec /usr/bin/foot -s
exec /usr/bin/gamemoded
exec /usr/bin/lxqt-policykit-agent
exec /usr/bin/swayidle
exec /usr/bin/swaync
exec ~/.config/sway/scripts/waysounds
exec /usr/bin/waybar
exec /usr/bin/batsignal

exec /usr/bin/dex -da | sed 's/^Executing command: //' | xargs -I {} swaymsg "exec {}"
