include "~/.config/sway/colors.conf"

font "Agave Nerd Font Propo" 10
titlebar_border_thickness 0
titlebar_padding 0 0

gaps inner 8
gaps outer 0

default_border pixel 1
default_floating_border pixel 1
floating_maximum_size -1 x -1

corner_radius 16

blur enable
blur_xray disable
blur_passes 2
blur_radius 5

shadows enable
shadows_on_csd enable
shadow_color #000000a1
shadow_blur_radius 16

layer_effects "waybar" {
  blur enable;
  blur_xray disable;
  blur_ignore_transparent enable
}

layer_effects "rofi" {
  blur enable;
  blur_xray disable;
  blur_ignore_transparent enable
  shadows enable;
  corner_radius 16;
}

layer_effects "swaync-notification-window" {
  blur enable;
  blur_xray disable;
  blur_ignore_transparent enable;
}

layer_effects "swaync-control-center" {
  blur enable;
  blur_xray disable;
  blur_ignore_transparent enable;
}

focus_follows_mouse no